discord:
  token: secret
  prefix: ¦
database:
  connection: "postgresql://parnassius:parnassius@localhost/parnassius"
logging:
  location: path/to/log/location
  filename: parnassius.log
  suffix: %Y_%m_%d
  level: INFO
guild:
  id: int
  emoji:
    yes: int
    what: int
    warn: int
    no: int
    neutral: int
  roles:
    exec: [int]
    muted: int